const foodTestData = [
  { category: 1, food: "소고기" },
  { category: 1, food: "돼지고기" },
  { category: 2, food: "달걀" },
  { category: 3, food: "쌀" },
  { category: 4, food: "아몬드" },
  { category: 5, food: "우유" },
  { category: 6, food: "빵" },
  { category: 7, food: "딸기잼" },
  { category: 8, food: "간장" },
  { category: 9, food: "올리브오일" },
  { category: 10, food: "우동" },
  { category: 11, food: "상추" },
  { category: 11, food: "시금치" },
  { category: 12, food: "사과" },
  { category: 12, food: "수박" },
  { category: 13, food: "배추김치" },
  { category: 14, food: "소주" },
  { category: 15, food: "생선" },
  { category: 16, food: "말린오징어" },
  { category: 17, food: "두부" },
  { category: 18, food: "콩나물" },
];