# Generated by Django 4.1.13 on 2024-03-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('category_pic', models.CharField(max_length=200)),
            ],
        ),
    ]
