# Generated by Django 4.1.13 on 2024-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_user'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='foods',
            name='food_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
