# Generated by Django 4.2.11 on 2024-03-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_user'),
        ('datas', '0003_foodingredient_delete_food_ingredient'),
    ]

    operations = [
    ]
